# Generated by Django 4.2.7 on 2023-11-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='description',
        ),
        migrations.RemoveField(
            model_name='react',
            name='title',
        ),
        migrations.AddField(
            model_name='react',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='react',
            name='auction_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='react',
            name='data_auction1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='react',
            name='data_leilao2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='react',
            name='initial_bid1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='react',
            name='initial_bid2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='react',
            name='neighborhood',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='react',
            name='open_or_closed',
            field=models.CharField(default='', max_length=500),
        ),
    ]
