# Generated by Django 4.2.7 on 2023-11-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlerapp', '0002_remove_react_description_remove_react_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='link_auction',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='react',
            name='link_image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
