# Generated by Django 4.2.7 on 2023-12-05 17:40

import django.core.validators
from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, unique=True, verbose_name='CPF')),
                ('cep', localflavor.br.models.BRPostalCodeField(max_length=9, unique=True, verbose_name='CEP')),
                ('cellphone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="O número de celular deve ser inserido no formato: '+999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
